### ISSUE TITLE
Fix mathematical errors in documentation

### ISSUE THREAD

**Issue by WoodrowShigeru** [sn1ppet/sn1ppet.github.io#10]
In the [documentation][1] you're writing stuff like "16:9 = 56.25%" – which is simply incorrect. 16:9 does not equal 56.25%.

What you mean is: "16:9 ≙ 56.25%" (s. [Correspondence][2])

[1]: http://sn1ppet.github.io/css/css-aspect-ratio.html
[2]: https://en.wikipedia.org/wiki/Correspondence_(mathematics)

**Comment by yannickoo** [comment]
Thank you :)

**Comment by axe312ger** [comment]
:+1:

**Comment by yannickoo** [comment]
:heart:

**Comment by WoodrowShigeru** [comment]
Wow, that was fast! <3

The same is true for the formula, though.

**Comment by yannickoo** [comment]
:)

<img width="167" alt="screen shot 2015-10-05 at 23 58 04" src="https://cloud.githubusercontent.com/assets/1086961/10294827/f0cf30d2-6bbc-11e5-8875-70fabbb871cf.png">

**Comment by axe312ger** [comment]
thx yannickoo
